CREATE USER 'publico'@'%' IDENTIFIED BY  '***';

GRANT SELECT ON `votacionespa` . * 
TO  'publico'@'%'
IDENTIFIED BY  '***'
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0 ;
